<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Article</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            text-align: center;
        }

        .article-content {
            margin-top: 30px;
        }

        .article-content h3 {
            font-size: 24px;
        }

        .article-content p {
            font-size: 16px;
            line-height: 1.6;
        }

        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <h1>Generated Article</h1>
    <div class="article-content">
        <h3>{{ $articleData['title'] ?? 'Untitled Article' }}</h3>
        <p><strong>Topic:</strong> {{ $articleData['subject'] }}</p>
        <p><strong>Audience:</strong> {{ $articleData['audience'] }}</p>
        <p><strong>Tone:</strong> {{ $articleData['tone'] }}</p>
        <p><strong>Length:</strong> {{ $articleData['length'] ?? 'Not Specified' }}</p>

        <h4>Article Content</h4>
        <p>{{ $articleContent }}</p>
    </div>

    <div class="footer">
        <p>Generated by DocCraft</p>
    </div>
</body>
</html>
