<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $blogTitle ?? 'Generated Blog' }} | DocCraft Pro</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&family=Playfair+Display:wght@500;600;700&display=swap');
        
        :root {
            --primary: #667eea;
            --primary-dark: #5649c0;
            --text: #2d3436;
            --light-text: #636e72;
            --border: #dfe6e9;
        }
        
        body {
            font-family: 'Poppins', sans-serif;
            line-height: 1.6;
            color: var(--text);
            padding: 1.5cm;
            font-size: 12pt;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid var(--primary);
        }
        
        .header h1 {
            font-family: 'Playfair Display', serif;
            color: var(--primary-dark);
            font-size: 24pt;
            margin-bottom: 10px;
        }
        
        .meta {
            font-size: 10pt;
            color: var(--light-text);
            margin-bottom: 5px;
        }
        
        .blog-content {
            margin-top: 30px;
            line-height: 1.8;
        }
        
        .blog-content p {
            margin-bottom: 15px;
            text-align: justify;
        }
        
        .blog-content h2 {
            font-family: 'Playfair Display', serif;
            color: var(--primary-dark);
            font-size: 18pt;
            margin: 30px 0 15px;
            border-bottom: 1px solid var(--border);
            padding-bottom: 5px;
        }
        
        .blog-content h3 {
            font-family: 'Playfair Display', serif;
            color: var(--primary-dark);
            font-size: 16pt;
            margin: 25px 0 12px;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid var(--border);
            font-size: 10pt;
            color: var(--light-text);
            text-align: center;
        }
        
        @page {
            size: A4;
            margin: 1.5cm;
        }
        
        @media print {
            body {
                padding: 0;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $blogTitle ?? 'Generated Blog Post' }}</h1>
        <div class="meta">Generated on {{ date('F j, Y') }} | DocCraft Pro</div>
    </div>
    
    <div class="blog-content">
        {!! nl2br(e($blogContent)) !!}
    </div>
    
    <div class="footer">
        <p>This document was generated by DocCraft Pro - Professional Content Generator</p>
    </div>
</body>
</html>